export const GET_CANDIDATES_KEY = "GET_CANDIDATES";
export const GET_CANDIDATE_BY_ID_KEY = "GET_CANDIDATE_BY_ID";
export const CREATE_CANDIDATE_KEY = "CREATE_CANDIDATE";
export const UPDATE_CANDIDATE_KEY = "UPDATE_CANDIDATE";
